[package]
name = "js-interpreter-backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
boa_engine = "0.20.0"
candid = "0.10"
ic-cdk = "0.18.3"
ic-cdk-timers = "0.12"
ic-wasi-polyfill = "0.9"
